# Generated by Django 5.2.1 on 2025-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_click_urltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.urltag'),
        ),
    ]
